### ISSUE TITLE
Query string support to List function

### ISSUE THREAD

**Issue by SlowLearner12** [CSCI-GA-2820-SP24-001/customers#36]
**As a** [developer,]
**I need** [to integrate query string support into our List function]  
**So that** [our service allows dynamic filtering based on user input]  
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [a properly formatted string]
 When [appropriate party is looking for customers]
 Then [the appropriate customer info is provided in an organized way]
```

**Comment by maiko-chin** [comment]
Given that the below are what we need to do:
• Add query capability to your model (in model.py)
• Add query string support to your List function (in routes.py)
Maybe we can combine this into a big story (larger estimate), or separate it based on model and routes?

**Comment by maiko-chin** [comment]
Updated heading to "Query string support to List function" from "Query string support" to call out the List function
