### ISSUE TITLE
Set up local Kubernetes Cluster

### ISSUE THREAD

**Issue by SlowLearner12** [CSCI-GA-2820-SP24-001/customers#38]
**As a** [developer]
**I need** [to set up a local Kubernetes K3S using the make cluster command ]  
**So that** [we are prepared for our application's deployment]  
   
 ### Details and Assumptions

Rec 3 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the developer has access to a terminal or command line
 When the developer runs the "make cluster" command
 Then a local Kubernetes cluster is set up and ready for application deployment
```

**Comment by SydneyKoby** [comment]
confirmed runnning with 'kubectl cluster-info' command

**Comment by SydneyKoby** [comment]
Created Deployment and pods as well
