### ISSUE TITLE
Create the folder and YML files for Kubernetes

### ISSUE THREAD

**Issue by SlowLearner12** [CSCI-GA-2820-SP24-001/customers#39]
**As a** [Developer]
**I need** [a proper ./k8s folder in the repository add all necessary Kubernetes manifest files for our application's deployment ]  
**So that** [kubernetes will know how to deploy our application]  
   
 ### Details and Assumptions
 * part of requirement 3 to deploy to Kubernetes
 ### Acceptance Criteria  
   
 ```gherkin
Given the repository contains a ./k8s folder
When all necessary Kubernetes manifest files are added for the application's deployment
Then the app is ready to deploy to kubernetes
```

**Comment by maiko-chin** [comment]
Just adding the details:
• Add manifest files for deployment: deployment.yaml, service.yaml, secrets.yaml, ingress.yaml, etc.
• Create postgres.yaml manifest
• Add a /health endpoint that returns {"status":"OK"} and 200_OK return code
