### ISSUE TITLE
Build a Model

### ISSUE THREAD

**Issue by SlowLearner12** [CSCI-GA-2820-SP24-001/customers#7]
**As a** Customer 
**I need** to have appropriate data stored in a logical way
**So that** have an account on this storefront and exist 
   
 ### Details and Assumptions
This database needs to cover all common data types that might be associated with an ecommerce customer

- id
- name
- address
- email

 ```gherkin
 Given [customers exist]
 When [customers log in, get created, or any other action spesific to customers]
 Then [relevant data spesific to the customer is available]
```

**Comment by maiko-chin** [comment]
Need to add
-customer id
-customer address

**Comment by maiko-chin** [comment]
Updated for the build a model to just be on the 4 basic categories:
- id
- name
- address
- email

Other categories will be in a new story
